// Generated by `buf generate` from the Open Match protos; the upstream comments
// are reflowed into Rust doc comments in a way clippy's doc lints reject, and
// regenerating the file would just reintroduce them.
#![allow(clippy::doc_lazy_continuation)]

include!("gen/openmatch.rs");
